### ISSUE TITLE
Routing mode options

### ISSUE THREAD

**Issue by Arevico** [SimplyEdit/simplyview#1]
It would be great if simply edit simplyview.routes supports an abstract routing mode (history disabled, or bound to an object)

**Comment by poef** [comment]
Could you describe a use case for this feature? I know the current component has very basic functionality, I'd like to keep it as simple as possible, while still complete enough for 80% of use cases out there.

**Comment by Arevico** [comment]
An example use case could be, if I want to include multiple components on the same page, but i want the orchestration of the routing be managed by a different framework.

Changes in url trough pushState() cannot be watched, except trough a wrapper function. Thus, if I want another component to react or to orchestrate routing, a configuration looks disabling this depence on pushstate seems required.

Examples as implemented by:
 - Vue -  https://router.vuejs.org/api/#mode
 - React - https://stackoverflow.com/questions/39721812/react-router-without-changing-url

**Comment by poef** [comment]
I think the simplest way to do that is to skip the global.addEventListener for popstate on line 70 and just call the simply.route.match() method where needed. And skip the addEventListener for click as well (line 95). I think it also makes it easier to use in different circumstances, so I'll add it to the roadmap :)

**Comment by poef** [comment]
I've updated simply.route so that it no longer automatically handles events. You must call simply.route.handleEvents() to do that. So now you can just skip this call and use simply.route.match() instead if simply.route.goto() and simply.route should behave itself :) Does this satisfy your request?

**Comment by Arevico** [comment]
Looks like this change will do for now, thanks
