### ISSUE TITLE
Documentation for transformers (data-simply-immediate)

### ISSUE THREAD

**Issue by MarcHagen** [SimplyEdit/simplyview#8]
After allotting of digging in the `simply.everything.js` I came across this piece of code.
https://github.com/SimplyEdit/simplyview/blob/3192c5107daa453191df2af1001faedc31580b03/js/simply.command.js#L61

Which is exactly what I was looking for! I wanted to filter out some data from a dataset.
I know already `data-simply-command` where the way to go for this. But found out it only triggers the command function after the input has changed and the input is unfocused.

I found it strange because there are listeners for the input event:
https://github.com/SimplyEdit/simplyview/blob/3192c5107daa453191df2af1001faedc31580b03/js/simply.command.js#L179-L182

So here I am asking to add `data-simply-immediate="true"` to the documentation so each input key triggers a command.

My example:
```html
<div class="input-group">
    <input type="search" class="form-control" data-simply-command="searchFilterTags" data-simply-immediate="true">
    <div class="input-group-btn">
        <button class="btn btn-primary" data-simply-command="searchFilterTags"><i class="glyphicon glyphicon-search"></i></button>
    </div>
</div>
<div data-simply-list="filtered">
    <template>
        <label class="btn btn-default">
            <input type="checkbox" class="server" name="addServers[]" value="" data-simply-field="serviceId" data-simply-content="attributes" data-simply-attributes="value">
            <span data-simply-field="assetTag">
        </label>
    </template>
</div>
```

```javascript
editor.commands.searchFilterTags = function (el) {
    const searchValue = el.tagName === 'INPUT' ? el.value : document.querySelector('input[data-simply-command="searchFilterTags"]').value
    const filteredServers = editor.pageData.servers

    editor.pageData.filtered = filteredServers.filter(o => o.assetTag.toLowerCase().includes(searchValue.toLowerCase()))
}
```

**Comment by poef** [comment]
Hi, thanks for the feedback, I did find the documentation for this feature on our reference (reference.simplyedit.io/simplyview/) but you are right, it is missing from the documentation included in this repository. I'll add the missing documentation asap. For your information, this is in the reference:

"By default commands on form inputs are only triggered on the change event. However, you can make them trigger on the input event, which means that every keystroke will immediately run the associated command. To do this, specify your command like this:

```<input type="text" 
    data-simply-command="someCommand" data-simply-immediate="true">```

**Comment by poef** [comment]
I've added the missing documentation, please let me know if you find any more stuff missing or incomplete.

**Comment by MarcHagen** [comment]
Awesome, thank you. I did search on the reference.simplyedit.io but gave no results.
Also, google en stuff didn't help. 
![image](https://github.com/SimplyEdit/simplyview/assets/980978/74847163-b58d-4bb3-b11a-7d59b9e5e18f)
